<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>JenkinsAsService.CustomActions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WixToolset.Dtf.CustomAction" Version="5.*" />
    <PackageReference Include="WixToolset.Dtf.WindowsInstaller" Version="5.*" />
    <PackageReference Include="AdysTech.CredentialManager" Version="2.6.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.0" />
  </ItemGroup>

</Project>
