name: Trivy

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '28 23 * * 6'

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    uses: ./.github/workflows/trivy-reusable.yml
    permissions:
      contents: read
      security-events: write
