name: OSV-Scanner

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '28 23 * * 6'

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OSV Scanner
        run: |
          curl -sSfL "https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64" -o osv-scanner
          chmod +x osv-scanner

      - name: Run OSV Scanner
        run: ./osv-scanner -r --skip-git --format sarif --output osv-results.sarif ./ || true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif
